### ISSUE TITLE
Captions on web examples

### ISSUE THREAD

**Issue by elliotarthur** [ObjectiveSubject/obsub#12]
Can these align to the left? Retaining the same style as the other captions (brochures, posters, stationery). Happy for the Mobile to stay centered as the nature of the mobile size and position.

**Comment by kpettinga** [comment]
@elliotarthur can you get me the captions that we need for the web screenshots for LocalData? Right now we're just using 1 caption for all the images in a slideshow.

**Comment by elliotarthur** [comment]
@kpettinga
For the marketing site use:
Homepage - _Local Data Homepage_
Action page - _Local Data Action Page_
Story - _Local Data Story Page_

For the Tool pages:
Tool1 - _Local Data Tool Login Page_
Tool2 - _Local Data Tool Landing Page_
Tool3 - _Local Data Survey Dashboard_
Tool4 - _Local Data Neighborhood Map page_
