### ISSUE TITLE
Oakland: Quote Needs delay

### ISSUE THREAD

**Issue by jalbertgagnier** [ObjectiveSubject/obsub#18]
hard to read fully in some contexts, if it took just a bit longer to come on screen it'd work better.

**Comment by jalbertgagnier** [comment]
![scroll2](https://cloud.githubusercontent.com/assets/1825143/12797495/3d730b14-ca92-11e5-99ed-977856e4fdca.png)
![scroll1](https://cloud.githubusercontent.com/assets/1825143/12797496/3d77d5d6-ca92-11e5-9abd-87b39d36babe.png)

**Comment by elliotarthur** [comment]
Hey @kpettinga with regards to the quote banners. Can these be hidden behind the main canvas at the begining of the scrolling? SO it's not waiting for you to hitch a ride. Exactly how it hides after you scroll past the image.
