### ISSUE TITLE
Scrollable website images

### ISSUE THREAD

**Issue by jalbertgagnier** [ObjectiveSubject/obsub#19]
Full length assets for website pages were created, let's have them so that we have `overflow: scroll;` almost like an iframe

**Comment by kpettinga** [comment]
@jalbertgagnier @elliotarthur 
The inspiration you guys had referenced for this earlier was a set of 3 devices (laptop, tablet, mobile) and the content in each screen moved as you scrolled down past it. Is that the kind of behavior you're wanting here? The alternative would be to create something where a user has more control and could just scroll each device at will by hovering it and using the scrollwheel.

Whichever direction you want to pursue, let me know how you're thinking about layout for this. Do we want users to be able to scroll _all_ the pages? Just one?

And finally, can you get me the image assets for the devices? SVGs like the mobile phone we currently have is fine.

**Comment by elliotarthur** [comment]
Hey @kpettinga, We think it'll be better to have the user use their scroll wheel over the image, giving it the behavior of a real site. I think all the pages should be able to scroll, keeping the same layout as we're currently using.

All the site images are full length and if you can use the browser bar you created in CSS would be perfect.

**Comment by kpettinga** [comment]
@elliotarthur I see. So to be clear, we want to keep them in their slideshows and have each be scrollable? I can't guarantee the feasibility of that or how that might turn out but will give it a shot. The fact that each image is already being manipulated by the JS for the slideshow adds to the complexity of doing something like this.

**Comment by kpettinga** [comment]
@jalbertgagnier @elliotarthur check out the site image slideshows on dev.objectivesubject.com/case-studies/city-of-oakland/

**Comment by elliotarthur** [comment]
Hey @kpettinga Just realized the images within the iPhone frames don't scroll. Can we apply the same scrollable containers for these?

**Comment by kpettinga** [comment]
@elliotarthur this should be all set.
