### ISSUE TITLE
Oakland Brochure covers should be 128bit PNG

### ISSUE THREAD

**Issue by jalbertgagnier** [ObjectiveSubject/obsub#20]

**Comment by elliotarthur** [comment]
@kpettinga These images have been over-written in the assets folder.

**Comment by kpettinga** [comment]
@elliotarthur @jalbertgagnier 
I've taken your new images and run them thru a compressor which is making it look a bit grainy still, especially on "The Flowers in our Parks" brochure (because of the blur I'm guessing). If we don't compress the images, they're 659kb and 2.5mb(!!), respectively, for standard and retina versions.

Are these being generated from a photoshop file? Maybe something in that file can be rasterized or optimizations can be made there first?

Of course, we could just say forget it and use the uncompressed ones. It will make the page a lot "heavier" to load though.

**Comment by elliotarthur** [comment]
I ran it through my compressor (ImageOptim) but it doesn't seem to reduce the size of the file, maybe because it's too large.

They are made through photoshop and I compressed them as much as possible. 

Is it bad practice to run such a large image for the site? Would like to retain the quality ;)

**Comment by kpettinga** [comment]
@elliotarthur yeah generally a rule of thumb for image sizes is to stay under ~200kb for big images. So the current ones are really pushing that, _especially_ the @2x. I wonder if a jpg would give us better luck.

**Comment by jalbertgagnier** [comment]
Problem with .jpg would be the bg color matching though, no?
On Tue, Feb 9, 2016 at 20:05 Kirk Pettinga notifications@github.com wrote:

> @elliotarthur https://github.com/elliotarthur yeah generally a rule of
> thumb for image sizes is to stay under ~200kb for big images. So the
> current ones are really pushing that, _especially_ the @2x
> https://github.com/2x. I wonder if a jpg would give us better luck.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ObjectiveSubject/obsub/issues/20#issuecomment-182154186
> .
> 
> ## 
> 
> _

David Jalbert-Gagnier
Principal — Objective Subject
David@ObjectiveSubject.com  @jalbertgagnier
+1 718 801-8076 direct   +1 718 496-4945 mobile

**Comment by kpettinga** [comment]
@jalbertgagnier I just exported jpgs and it's looking good on my end. With significantly smaller file sizes (289kb 1x and 383kb 2x).

**Comment by elliotarthur** [comment]
Noticing the background is slightly off now it's jpg. I had that issue with it during design stages.

![image](https://cloud.githubusercontent.com/assets/12611145/12950012/06f8af0c-cfd9-11e5-95bf-b311afbd17be.png)

**Comment by jalbertgagnier** [comment]
Would it make sense to low source the JPG until the right png loads?
http://www.htmlgoodies.com/tutorials/web_graphics/article.php/3479971/So-You-Want-LowSrc-Huh.htm
(I
know this recommendation dates me)

On Wed, Feb 10, 2016 at 9:31 AM elliotarthur notifications@github.com
wrote:

> Noticing the background is slightly off now it's jpg. I had that issue
> with it during design stages.
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/12611145/12950012/06f8af0c-cfd9-11e5-95bf-b311afbd17be.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ObjectiveSubject/obsub/issues/20#issuecomment-182398147
> .
> 
> ## 
> 
> _

David Jalbert-Gagnier
Principal — Objective Subject
David@ObjectiveSubject.com  @jalbertgagnier
+1 718 801-8076 direct   +1 718 496-4945 mobile

**Comment by kpettinga** [comment]
@jalbertgagnier I didn't know about lowsrc! Going to keep that one in my back pocket. But I think the easiest solution in this case is to just match the background color of the page to the .jpg. It's a _very_ slight shift. Feel free to re-open the issue if it's not satisfactory.

**Comment by jalbertgagnier** [comment]
I believe matching is actually not an option because of the way JPG
compression works and is handled by different browsers in differing color
profiles.

On Wed, Feb 10, 2016 at 8:34 PM Kirk Pettinga notifications@github.com
wrote:

> Closed #20 https://github.com/ObjectiveSubject/obsub/issues/20.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ObjectiveSubject/obsub/issues/20#event-546639093.
> 
> ## 
> 
> _

David Jalbert-Gagnier
Principal — Objective Subject
David@ObjectiveSubject.com  @jalbertgagnier
+1 718 801-8076 direct   +1 718 496-4945 mobile
