### ISSUE TITLE
Homepage Logos not Retina

### ISSUE THREAD

**Issue by jalbertgagnier** [ObjectiveSubject/obsub#22]
SVGs are provided in assets folder (Only AP & WS currently are)

**Comment by ObSubTech** [comment]
Still seeing non-retina assets, is it just not pushed?
On Thu, Feb 4, 2016 at 01:33 Kirk Pettinga notifications@github.com wrote:

> Closed #22 https://github.com/ObjectiveSubject/obsub/issues/22.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ObjectiveSubject/obsub/issues/22#event-538714714.
> 
> ## 
> 
> _

David Jalbert-Gagnier
Principal — Objective Subject
David@ObjectiveSubject.com  @jalbertgagnier
+1 718 801-8076 direct   +1 718 496-4945 mobile
