### ISSUE TITLE
Mock up OZY movie integration on homepage

### ISSUE THREAD

**Issue by jalbertgagnier** [ObjectiveSubject/obsub#23]
Same treatment for Oakland tree progress animation on case study

**Comment by elliotarthur** [comment]
@jalbertgagnier Take a look at the mock up. If you're happy, then the image asset is in the folder ready for @kpettinga to implement. 

![osweb-homepage](https://cloud.githubusercontent.com/assets/12611145/12800479/452d8a62-caa3-11e5-8d6c-00833caf3dcf.png)

**Comment by elliotarthur** [comment]
and whether you want to add a little blurb below?!

**Comment by jalbertgagnier** [comment]
> _Watch principal David Jalbert-Gagnier explain our vision in this 2:27 video from OZY._
> links to http://www.ozy.com/video/play/better-logos-better-government/67599 in new window

**Comment by jalbertgagnier** [comment]
Looks good otherwise.
