### ISSUE TITLE
Animated Compass Logo

### ISSUE THREAD

**Issue by jalbertgagnier** [ObjectiveSubject/obsub#3]
Logo: Use file: LD Compass Animation 20140228 DJG built in Hype <tumult.com/hype/>, might make sense to add the wordmark inside Hype. Open to other animation solutions of course.

**Comment by kpettinga** [comment]
@jalbertgagnier what if we animated this to follow your mouse ... !?

**Comment by jalbertgagnier** [comment]
That'd be cool. As long as there is the ease back to make it feel like a
compass (that's the point of the animation, emphasizing its compass-ness).

On Tue, Feb 9, 2016 at 2:47 AM Kirk Pettinga notifications@github.com
wrote:

> @jalbertgagnier https://github.com/jalbertgagnier what if we animated
> this to follow your mouse ... !?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ObjectiveSubject/obsub/issues/3#issuecomment-181749370
> .
> 
> ## 
> 
> _

David Jalbert-Gagnier
Principal — Objective Subject
David@ObjectiveSubject.com  @jalbertgagnier
+1 718 801-8076 direct   +1 718 496-4945 mobile

**Comment by kpettinga** [comment]
Oh ok. I was thinking it would just follow your mouse all the time.

**Comment by kpettinga** [comment]
Just implemented an interactive compass that responds to your mouse position if you're hovering the white container. Snaps back when you're not hovering.
http://dev.objectivesubject.com/case-studies/localdata

**Comment by jalbertgagnier** [comment]
Hi Kirk,

The movement is spot on, but I’m wondering if we need the interaction with the mouse. It seems a little much and might mean the wrong thing (a compass that lost its north, etc.). Can we just keep the movement and have it be triggered by it being scrolled to? I think that might be just the right movement.
