### ISSUE TITLE
Homepage: Provide web assets

### ISSUE THREAD

**Issue by jalbertgagnier** [ObjectiveSubject/obsub#30]
TJ, nytEDU and WS in our new look (mix of browser/tablet/phone).

**Comment by elliotarthur** [comment]
@kpettinga Assets are in the folder. With NYT, I've numbered them for their order, so GIF first, TimesJourneys next then Edu last. Stacked on top of one another.

Worldstrides hasd the same convention.

**Comment by kpettinga** [comment]
@elliotarthur it doesn't appear that the gifs you provided have looping enabled. they just run thru once.

**Comment by kpettinga** [comment]
@elliotarthur @jalbertgagnier I feel like i did what you're asking here but feel free to re-open if I missed something.

**Comment by elliotarthur** [comment]
@kpettinga I think you're right with having them loop. So i've updated the GIFs. Below are the assets which we've reworked for the homepage.

NYT: Replace GIF with the brand guidelines as a booklet.
AP: Remove GIF altogether, so only left with the monitor image.
CFR: Add image below text. CFR-@2x.png.
BAM: Replace GIF with the new GIF in folder.
WS: Replace site image with new site image.

**Comment by elliotarthur** [comment]
New NYT asset to replace the gif: nyt1-@2x.png
