### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by elliotarthur** [ObjectiveSubject/obsub#31]
Hey @kpettinga could we modify the navigation so the text is aligned with the cards. So horizontally aligned to the browser and left align to the text. Also can the behavior be the same as how the "opportunities, process, solution"? 

Then scrap the image thumbnails.

Image to help!

![osweb-navigation-1](https://cloud.githubusercontent.com/assets/12611145/12800218/69b8da8c-caa1-11e5-9505-2af376704d6b.png)

**Comment by kpettinga** [comment]
@elliotarthur you can see this up on the site now. What do you think, however, about slightly adjusting the type like the screen grab below? Just feel like "featured projects" is more of a _label_ than something you click and lining it all up to the same left rule makes it feel a bit more "locked" together. Open to what you think...
![image](https://cloud.githubusercontent.com/assets/1746410/12942657/46390d8e-d00f-11e5-85dd-c06d98e09c52.png)

**Comment by elliotarthur** [comment]
@kpettinga True. Although we also use futura as headers elsewhere such as "media" "arts" on the home page and "process" "solution". I like how you've got it currently.
