### ISSUE TITLE
Images which are not @2x

### ISSUE THREAD

**Issue by elliotarthur** [ObjectiveSubject/obsub#32]
Oakland:
Brochures (replaced image to removed dither)
Root system (SVG)

DBPS:
Mobile images

**Comment by kpettinga** [comment]
@elliotarthur see #20 about brochures. 
re: Root System svg, the file you exported just comes out as a solid green rectangle with no pattern. I tried to take a look in illustrator but the object is pretty complex. not sure what the issue is.

**Comment by elliotarthur** [comment]
Pattern-@2x.png
Pattern.png

in the Oakland folder.

**Comment by kpettinga** [comment]
@elliotarthur thanks!
