### ISSUE TITLE
About: Picture of Sam with red dot?

### ISSUE THREAD

**Issue by jalbertgagnier** [ObjectiveSubject/obsub#36]
@elliotarthur did we like this (i kind of did). Does @kpettinga have the artwork?

**Comment by elliotarthur** [comment]
Yeah, it was a nice addition to the recognition section. I've exported it out as the same dimensions as the homepage images. Here's a screen shot of how it should align to the layout.

![screen shot 2016-02-04 at 12 48 01 pm](https://cloud.githubusercontent.com/assets/12611145/12824235/411dbfaa-cb3e-11e5-9ce5-54ba0f31b006.png)
