### ISSUE TITLE
BPS: Supply 3 photos of billboards

### ISSUE THREAD

**Issue by jalbertgagnier** [ObjectiveSubject/obsub#40]

**Comment by elliotarthur** [comment]
3 photos in the DBPS folder. If we create another carousel with the same width as the site examples after the mobile. Include photo credit inside the image too. Screen shot for example.

![screen shot 2016-02-04 at 4 02 49 pm](https://cloud.githubusercontent.com/assets/12611145/12830001/0a15d37c-cb5b-11e5-96ae-6c19031963a3.png)

**Comment by jalbertgagnier** [comment]
Looks great

_

David Jalbert-Gagnier
Principal — Objective Subject
David@ObjectiveSubject.com  @jalbertgagnier

+1 718 801-8076 direct   +1 718 496-4945 mobile

**Comment by jalbertgagnier** [comment]
Text caption style doesn't match mockup or what we are using elsewhere.

**Comment by kpettinga** [comment]
@jalbertgagnier I took away the italics and adjusted the opacity to 0.3 (to match the Oakland hero image credit). In terms of alignment though, because the text is inside of a slide, there's no way to make it align with the content outside of the slideshow, at least not consistently, which is why I aligned it right.

**Comment by jalbertgagnier** [comment]
Looks good.

On Wed, Feb 10, 2016 at 5:09 AM Kirk Pettinga notifications@github.com
wrote:

> @jalbertgagnier https://github.com/jalbertgagnier I took away the
> italics and adjusted the opacity to 0.3 (to match the Oakland hero image
> credit). In terms of alignment though, because the text is inside of a
> slide, there's no way to make it align with the content outside of the
> slideshow, at least not consistently, which is why I aligned it right.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ObjectiveSubject/obsub/issues/40#issuecomment-182290662
> .
> 
> ## 
> 
> _

David Jalbert-Gagnier
Principal — Objective Subject
David@ObjectiveSubject.com  @jalbertgagnier
+1 718 801-8076 direct   +1 718 496-4945 mobile
