### ISSUE TITLE
Homepage: Image tweeks

### ISSUE THREAD

**Issue by elliotarthur** [ObjectiveSubject/obsub#46]
@kpettinga 
NYT: Push the booklet so it aligns with the text. Add the browser bar for Times Journeys.
CFR: Can this image be the same size as the others, should overhang out of the text container and aligns with the NYT image above it.
BAM: Nudge it up so the image aligns with the text.
Gibney: Push the booklet so it aligns with the text.
World Strides: Push the browser down so it aligns with the text.

Think we should remove the outer glow as we're not using this anywhere else.

**Comment by kpettinga** [comment]
@elliotarthur I added the drop-shadow because some of the site images seemed to not stand off the page background well enough. 
**i.e.**
![image](https://cloud.githubusercontent.com/assets/1746410/12937826/3b79e3e4-cfdf-11e5-964b-fce460ea013e.png)

@jalbertgagnier thoughts?

**Comment by jalbertgagnier** [comment]
White outline? Maybe we need a different image for CFR. We're you able to
retrieve our old site?

On Tue, Feb 9, 2016 at 22:15 Kirk Pettinga notifications@github.com wrote:

> @elliotarthur https://github.com/elliotarthur I added the drop-shadow
> because some of the site images seemed to not stand off the page background
> well enough.
> _i.e._
> [image: image]
> https://cloud.githubusercontent.com/assets/1746410/12937826/3b79e3e4-cfdf-11e5-964b-fce460ea013e.png
> 
> @jalbertgagnier https://github.com/jalbertgagnier thoughts?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ObjectiveSubject/obsub/issues/46#issuecomment-182179296
> .
> 
> ## 
> 
> _

David Jalbert-Gagnier
Principal — Objective Subject
David@ObjectiveSubject.com  @jalbertgagnier
+1 718 801-8076 direct   +1 718 496-4945 mobile

**Comment by elliotarthur** [comment]
@kpettinga NYT Times Journeys is in the folder, with the browser.
@jalbertgagnier I think a white border will work. I don't know what image will represent our work and relationship with CFR in a broader sense.

**Comment by kpettinga** [comment]
thanks @elliotarthur 

here's a preview with a white border: 
![image](https://cloud.githubusercontent.com/assets/1746410/12995124/a0590e4c-d157-11e5-8623-2eb18c64aa03.png)

Doesn't really seem work to me, especially b/c it wraps around the browser bar. Is a box shadow really that bad? I could lighten it.

**Comment by elliotarthur** [comment]
Are you able to add a white border via photoshop!? That way it won't wrap the browser.

**Comment by elliotarthur** [comment]
Sorry @kpettinga, but noticed an issue with the NYT spread image. There was a layer when I exported visible, which is making the spread much darker than it should be. I've replaced the files in the folder. Also replaced the BAM GIF, so it has a subtle transition between the frames now.

If you could re-upload them, that'll be great. 
Thanks
