### ISSUE TITLE
Oakland: Text change

### ISSUE THREAD

**Issue by elliotarthur** [ObjectiveSubject/obsub#47]
@kpettinga @jalbertgagnier How do you feel about having the design portfolio link and the text "_We continue to support the City as it improves the quality of its visual communication._" below the Pattern Portfolio screen carousel?

It feels more like a conclusion and the sunset scene in a movie...

**Comment by jalbertgagnier** [comment]
Sure. I'm also not sure about the positioning of the 2 links as it is...

On Wed, Feb 10, 2016 at 10:03 AM elliotarthur notifications@github.com
wrote:

> Assigned #47 https://github.com/ObjectiveSubject/obsub/issues/47 to
> @jalbertgagnier https://github.com/jalbertgagnier.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ObjectiveSubject/obsub/issues/47#event-545876646.
> 
> ## 
> 
> _

David Jalbert-Gagnier
Principal — Objective Subject
David@ObjectiveSubject.com  @jalbertgagnier
+1 718 801-8076 direct   +1 718 496-4945 mobile
