### ISSUE TITLE
Weird typo: 2 at top left corner

### ISSUE THREAD

**Issue by jalbertgagnier** [ObjectiveSubject/obsub#48]
on homepage, in both ff and safari
<img width="1317" alt="number2" src="https://cloud.githubusercontent.com/assets/1825143/13123326/a22f400c-d589-11e5-9aff-6be0ffcc8e17.png">

**Comment by kpettinga** [comment]
hey @jalbertgagnier could you confirm its happening on other computers? I can't replicate it.
Also maybe try to find it in your inspector and take a screenshot for me?

**Comment by jalbertgagnier** [comment]
seems to only happen on mine so far. tried iPhone and Dat's PC Thinkpad.
<img width="1367" alt="before" src="https://cloud.githubusercontent.com/assets/1825143/13134684/370fb150-d5d7-11e5-97ec-f89c46645604.png">

**Comment by kpettinga** [comment]
try clearing your browser cache if you haven't already. im going to clear
the varnish cache in wodrpess as well.

**Comment by kpettinga** [comment]
@jalbertgagnier this still happening for you?

**Comment by jalbertgagnier** [comment]
It is!

And also on a newly installed browser (Firefox on iOS), and on Aaron's computer too!
![img_3301](https://cloud.githubusercontent.com/assets/1825143/13209286/4db2c66a-d8f0-11e5-87d1-34dd2dcada29.jpg)
![img_3300](https://cloud.githubusercontent.com/assets/1825143/13209287/4db88a82-d8f0-11e5-8f8b-c7e9291f1007.jpg)

**Comment by jalbertgagnier** [comment]
FWIW, in my inspector I was seeing it next to the `:: Below` mark, so maybe it's something to do with JS?

<img width="1367" alt="before" src="https://cloud.githubusercontent.com/assets/1825143/13209406/78f9c386-d8f1-11e5-97f1-16606e7f0740.png">

**Comment by kpettinga** [comment]
Found it! It was in indicator of screen dpi in the CSS.
