### ISSUE TITLE
White in GIF

### ISSUE THREAD

**Issue by jalbertgagnier** [ObjectiveSubject/obsub#50]
Hey @elliotarthur it seems there's a white artifact in the animated gif for BAM

![img_3305](https://cloud.githubusercontent.com/assets/1825143/13209573/5818f2b6-d8f3-11e5-981e-b1509e0cf9fe.jpg)

**Comment by elliotarthur** [comment]
@jalbertgagnier That's strange, It's not replicating in the PSD or the GIF files I created?! I'm also noticing it's only showing on mobile applications and not my desktop browsers. 

@kpettinga do you know why this is happening?

**Comment by kpettinga** [comment]
That is _super_ weird. My guess is that is has something to do with the way iOS is handling the animated gif. I thought about maybe adjusting some settings on the exported gif but changing anything just seems to reduce the quality. @jalbertgagnier is it happening on your (retina) macbook? I'm curious if this is just a mobile issue or a retina issue.

Worst case I could just build a custom little css animation with a regular png sprite.

**Comment by elliotarthur** [comment]
@kpettinga It doesn't happen on my retina macbook with both Chrome and Safri.

**Comment by kpettinga** [comment]
@elliotarthur @jalbertgagnier take a peek at [the dev site](http://dev.objectivesubject.com/)
I ditched the gif and created a CSS animation for this.
