### ISSUE TITLE
New Case Study image assets

### ISSUE THREAD

**Issue by kpettinga** [ObjectiveSubject/obsub#53]
Hey Elliot, could you get me these assets for the AP and CFR case studies?

**AP**
- **Historical AP Logos**. Just gather them into one folder for me because I'm going to make an image sprite. 
  ![image](https://cloud.githubusercontent.com/assets/1746410/13942042/bcdb82b0-f020-11e5-9110-28cc8f6ef313.png)

**CFR**
- **Building images**
  ![image](https://cloud.githubusercontent.com/assets/1746410/13942106/48296b16-f021-11e5-8f68-dd99545f7414.png)

**Comment by elliotarthur** [comment]
Hey @kpettinga all those images are saved in their respected folders.

Any issues let me know.
