### ISSUE TITLE
CFR - Typographic breakdown

### ISSUE THREAD

**Issue by elliotarthur** [ObjectiveSubject/obsub#54]
Hey @kpettinga the large characters defining which typeface is Haarlemmer, Times and Georgia seems to be low quality on retina screens, same with the circles noting the anatomy of each character. Do you need assets from me regarding these? I'm assuming you probably used the same development process as the CFR guidelines right?

**Comment by kpettinga** [comment]
@elliotarthur, This should be all set. Take a look with your machine and let me know.

**Comment by elliotarthur** [comment]
Hey @kpettinga, I noticed the letters were jumping around (due to my poor asset creation) so I've resupplied them in the CFR folder. Hopefully this will sort that occurring. Thanks!

**Comment by kpettinga** [comment]
@elliotarthur this should be all set
